// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ3ewUvXpTb21CsyWCKJ-QTIPDhDCckSs',
    appId: '1:543415277890:web:aa49266f7dc933acd910db',
    messagingSenderId: '543415277890',
    projectId: 'emaillink-c3ec5',
    authDomain: 'emaillink-c3ec5.firebaseapp.com',
    storageBucket: 'emaillink-c3ec5.firebasestorage.app',
    measurementId: 'G-W0T10GBTJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqz3nS2z-gVHdUxsPeWKpveeTjdYgboZE',
    appId: '1:543415277890:android:d12dd7960f2c3b7ed910db',
    messagingSenderId: '543415277890',
    projectId: 'emaillink-c3ec5',
    storageBucket: 'emaillink-c3ec5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yBebydfd4iwHB07xDfRMI-FoaQeMiBQ',
    appId: '1:543415277890:ios:3e0de7704bfa1f9fd910db',
    messagingSenderId: '543415277890',
    projectId: 'emaillink-c3ec5',
    storageBucket: 'emaillink-c3ec5.firebasestorage.app',
    iosBundleId: 'com.example.tekort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0yBebydfd4iwHB07xDfRMI-FoaQeMiBQ',
    appId: '1:543415277890:ios:3e0de7704bfa1f9fd910db',
    messagingSenderId: '543415277890',
    projectId: 'emaillink-c3ec5',
    storageBucket: 'emaillink-c3ec5.firebasestorage.app',
    iosBundleId: 'com.example.tekort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNYcYFLBFRulW6YtZGQ8xGInfGEwGMOf0',
    appId: '1:543415277890:web:8bd0ac98fb9ae052d910db',
    messagingSenderId: '543415277890',
    projectId: 'emaillink-c3ec5',
    authDomain: 'emaillink-c3ec5.firebaseapp.com',
    storageBucket: 'emaillink-c3ec5.firebasestorage.app',
    measurementId: 'G-XJ5Y98EKNW',
  );
}

















// // import 'package:device_preview/device_preview.dart';
// // import 'package:webapp/app/controllers/theme_controller.dart';
// // import 'package:webapp/app/data/constants/constants.dart';
// // import 'package:webapp/app/routes/app_routes.dart';
// // import 'package:webapp/app/services/theme_services.dart';
// // import 'package:flutter/foundation.dart';
// // import 'package:flutter/material.dart';
// // import 'package:flutter/services.dart';
// // import 'package:flutter_screenutil/flutter_screenutil.dart';
// // import 'package:get/get.dart';
// // import 'package:webapp/app/data/constants/app_theme.dart';

// // void main() async {
// //   WidgetsFlutterBinding.ensureInitialized();
// //   SystemChrome.setSystemUIOverlayStyle(defaultOverlay);
// //   await SystemChrome.setPreferredOrientations(
// //     [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
// //   );
// //   runApp(
// //     kIsWeb
// //         ? DevicePreview(
// //             enabled: true,
// //             builder: (context) => const Main(),
// //           )
// //         : const Main(),
// //   );
// // }

// // class Main extends StatelessWidget {
// //   const Main({super.key});

// //   @override
// //   Widget build(BuildContext context) {
// //     final themeController = Get.put(ThemeController());
// //     print(themeController.theme);
// //     return ScreenUtilInit(
// //       designSize: const Size(375, 844),
// //       useInheritedMediaQuery: true,
// //       minTextAdapt: true,
// //       builder: (context, child) {
// //         return GestureDetector(
// //           behavior: HitTestBehavior.opaque,
// //           onTap: () {
// //             FocusManager.instance.primaryFocus?.unfocus();
// //           },
// //           child: GetMaterialApp(
// //             useInheritedMediaQuery: true,
// //             locale: DevicePreview.locale(context),
// //             builder: DevicePreview.appBuilder,
// //             title: 'Door Hub',
// //             debugShowCheckedModeBanner: false,
// //             scrollBehavior: const ScrollBehavior()
// //                 .copyWith(physics: const BouncingScrollPhysics()),
// //             defaultTransition: Transition.fadeIn,
// //             theme: AppTheme.lightTheme,
// //             darkTheme: AppTheme.darkTheme,
// //             themeMode: getThemeMode(themeController.theme),
// //             initialRoute: AppRoutes.getOnboardingRoute(),
// //             getPages: AppRoutes.routes,
// //           ),
// //         );
// //       },
// //     );
// //   }
// // }



// import 'package:flutter/material.dart';
// import 'package:flutter/material.dart';
// import 'package:scratcher/widgets.dart';

// void main() {
//   runApp(MyApp());
// }



// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Attendance Tracker',
//       debugShowCheckedModeBanner: false,
//       home: CustomScratcher(),
//     );
//   }
// }
// // Dummy users and attendance data
// List<Map<String, dynamic>> users = [
//   {"id": "admin01", "username": "admin", "password": "admin123", "role": "admin"},
//   {"id": "emp01", "username": "user", "password": "user123", "role": "employee"},
//   {"id": "emp02", "username": "User", "password": "User123", "role": "employee"},
// ];
// List<Map<String, dynamic>> attendanceData = [];
// class LoginScreen extends StatefulWidget {
//   @override
//   State<LoginScreen> createState() => _LoginScreenState();
// }
// class _LoginScreenState extends State<LoginScreen> {
//   final _usernameController = TextEditingController();
//   final _passwordController = TextEditingController();
//   String error = '';
//   void login() {
//     String username = _usernameController.text.trim();
//     String password = _passwordController.text.trim();
//     var matchedUser = users.firstWhere(
//       (u) => u['username'] == username && u['password'] == password,
//       orElse: () => {},
//     );
//     if (matchedUser.isNotEmpty) {
//       if (matchedUser['role'] == 'admin') {
//         Navigator.pushReplacement(
//           context,
//           MaterialPageRoute(builder: (_) => AdminDashboard()),
//         );
//       } else {
//         Navigator.pushReplacement(
//           context,
//           MaterialPageRoute(
//             builder: (_) => EmployeeDashboard(user: matchedUser),
//           ),
//         );
//       }
//     } else {
//       setState(() {
//         error = 'Invalid credentials!';
//       });
//     }
//   }
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: Text("Login")),
//       body: Padding(
//         padding: const EdgeInsets.all(20),
//         child: Column(
//           children: [
//             TextField(controller: _usernameController, decoration: InputDecoration(labelText: "Username")),
//             TextField(controller: _passwordController, decoration: InputDecoration(labelText: "Password"), obscureText: true),
//             SizedBox(height: 20),
//             ElevatedButton(onPressed: login, child: Text("Login")),
//             if (error.isNotEmpty) ...[
//               SizedBox(height: 10),
//               Text(error, style: TextStyle(color: Colors.red)),
//             ],
//           ],
//         ),
//       ),
//     );
//   }
// }
// class AdminDashboard extends StatefulWidget {
//   @override
//   State<AdminDashboard> createState() => _AdminDashboardState();
// }

// class _AdminDashboardState extends State<AdminDashboard> {
//   void addEmployeeDialog() {
//     final _usernameController = TextEditingController();
//     final _passwordController = TextEditingController();

//     showDialog(
//       context: context,
//       builder: (_) => AlertDialog(
//         title: Text("Add New Employee"),
//         content: Column(
//           mainAxisSize: MainAxisSize.min,
//           children: [
//             TextField(controller: _usernameController, decoration: InputDecoration(labelText: "Username")),
//             TextField(controller: _passwordController, decoration: InputDecoration(labelText: "Password")),
//           ],
//         ),
//         actions: [
//           TextButton(onPressed: () => Navigator.pop(context), child: Text("Cancel")),
//           ElevatedButton(
//             onPressed: () {
//               setState(() {
//                 users.add({
//                   "id": "emp${users.length + 1}",
//                   "username": _usernameController.text,
//                   "password": _passwordController.text,
//                   "role": "employee",
//                 });
//               });
//               Navigator.pop(context);
//             },
//             child: Text("Add"),
//           ),
//         ],
//       ),
//     );
//   }

//   void editEmployeeDialog(Map<String, dynamic> user) {
//     final _usernameController = TextEditingController(text: user['username']);
//     final _passwordController = TextEditingController(text: user['password']);

//     showDialog(
//       context: context,
//       builder: (_) => AlertDialog(
//         title: Text("Edit Employee"),
//         content: Column(
//           mainAxisSize: MainAxisSize.min,
//           children: [
//             TextField(controller: _usernameController, decoration: InputDecoration(labelText: "Username")),
//             TextField(controller: _passwordController, decoration: InputDecoration(labelText: "Password")),
//           ],
//         ),
//         actions: [
//           TextButton(onPressed: () => Navigator.pop(context), child: Text("Cancel")),
//           ElevatedButton(
//             onPressed: () {
//               setState(() {
//                 user['username'] = _usernameController.text;
//                 user['password'] = _passwordController.text;
//               });
//               Navigator.pop(context);
//             },
//             child: Text("Save"),
//           ),
//         ],
//       ),
//     );
//   }

//   void deleteEmployee(Map<String, dynamic> user) {
//     showDialog(
//       context: context,
//       builder: (_) => AlertDialog(
//         title: Text("Delete Employee"),
//         content: Text("Are you sure you want to delete ${user['username']}?"),
//         actions: [
//           TextButton(onPressed: () => Navigator.pop(context), child: Text("Cancel")),
//           ElevatedButton(
//             onPressed: () {
//               setState(() {
//                 users.remove(user);
//                 attendanceData.removeWhere((a) => a['userId'] == user['id']);
//               });
//               Navigator.pop(context);
//             },
//             child: Text("Delete"),
//           ),
//         ],
//       ),
//     );
//   }

//   List<Map<String, dynamic>> getEmployees() {
//     return users.where((u) => u['role'] == 'employee').toList();
//   }

//   List<String> getEmployeeName(String userId) {
//     var user = users.firstWhere((u) => u['id'] == userId, orElse: () => {});
//     return user.isNotEmpty ? [user['username']] : ["Unknown"];
//   }

//   @override
//   Widget build(BuildContext context) {
//     var employees = getEmployees();

//     return Scaffold(
//       appBar: AppBar(
//         title: Text("Admin Dashboard"),
//         actions: [
//           IconButton(
//             icon: Icon(Icons.logout),
//             onPressed: () {
//               Navigator.pushAndRemoveUntil(
//                 context,
//                 MaterialPageRoute(builder: (_) => LoginScreen()),
//                 (route) => false,
//               );
//             },
//           ),
//         ],
//       ),
//       floatingActionButton: FloatingActionButton(
//         onPressed: addEmployeeDialog,
//         child: Icon(Icons.add),
//         tooltip: "Add Employee",
//       ),
//       body: Padding(
//         padding: const EdgeInsets.all(10),
//         child: ListView(
//           children: [
//             Text("👥 Employees", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
//             ...employees.map((user) {
//               return Card(
//                 child: ListTile(
//                   title: Text(user['username']),
//                   subtitle: Text("ID: ${user['id']}"),
//                   trailing: Row(
//                     mainAxisSize: MainAxisSize.min,
//                     children: [
//                       IconButton(onPressed: () => editEmployeeDialog(user), icon: Icon(Icons.edit, color: Colors.blue)),
//                       IconButton(onPressed: () => deleteEmployee(user), icon: Icon(Icons.delete, color: Colors.red)),
//                     ],
//                   ),
//                 ),
//               );
//             }),
//             SizedBox(height: 20),
//             Divider(),
//             Text("🕒 Attendance Records", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
//             ...attendanceData.map((record) {
//               return Card(
//                 child: ListTile(
//                   title: Text("${getEmployeeName(record['userId']).first} - ${record['date']}"),
//                   subtitle: Text("Day In: ${record['dayIn'] ?? '--'} | Day Out: ${record['dayOut'] ?? '--'}"),
//                 ),
//               );
//             }).toList(),
//           ],
//         ),
//       ),
//     );
//   }
// }


// class EmployeeDashboard extends StatefulWidget {
//   final Map<String, dynamic> user;

//   const EmployeeDashboard({required this.user});

//   @override
//   State<EmployeeDashboard> createState() => _EmployeeDashboardState();
// }

// class _EmployeeDashboardState extends State<EmployeeDashboard> {
//   String today = DateTime.now().toString().split(' ')[0];
//   Map<String, dynamic>? todayRecord;

//   @override
//   void initState() {
//     super.initState();
//     todayRecord = attendanceData.firstWhere(
//       (a) => a['userId'] == widget.user['id'] && a['date'] == today,
//       orElse: () => {},
//     );
//   }

//   void markIn() {
//     if (todayRecord == null || todayRecord!.isEmpty) {
//       var newRecord = {
//         "userId": widget.user['id'],
//         "date": today,
//         "dayIn": TimeOfDay.now().format(context),
//         "dayOut": null,
//       };
//       attendanceData.add(newRecord);
//       setState(() {
//         todayRecord = newRecord;
//       });
//     }
//   }

//   void markOut() {
//     if (todayRecord != null && todayRecord!['dayOut'] == null) {
//       setState(() {
//         todayRecord!['dayOut'] = TimeOfDay.now().format(context);
//       });
//     }
//   }

//   String calculateWorkingHours(String inTime, String outTime) {
//     final now = DateTime.now();
//     final inParts = inTime.split(":");
//     final outParts = outTime.split(":");

//     final inHour = int.parse(inParts[0]);
//     final inMinute = int.parse(inParts[1].split(" ")[0]);
//     final inPeriod = inParts[1].split(" ")[1];

//     final outHour = int.parse(outParts[0]);
//     final outMinute = int.parse(outParts[1].split(" ")[0]);
//     final outPeriod = outParts[1].split(" ")[1];

//     DateTime inDateTime = DateTime(
//         now.year,
//         now.month,
//         now.day,
//         inPeriod == "PM" && inHour != 12 ? inHour + 12 : inHour,
//         inMinute);

//     DateTime outDateTime = DateTime(
//         now.year,
//         now.month,
//         now.day,
//         outPeriod == "PM" && outHour != 12 ? outHour + 12 : outHour,
//         outMinute);

//     final diff = outDateTime.difference(inDateTime);
//     final hours = diff.inHours;
//     final minutes = diff.inMinutes % 60;
//     return "$hours hrs $minutes mins";
//   }

//   @override
//   Widget build(BuildContext context) {
//     bool isInDone = todayRecord != null && todayRecord!['dayIn'] != null;
//     bool isOutDone = todayRecord != null && todayRecord!['dayOut'] != null;

//     String workingHours = "--";
//     if (isInDone && isOutDone) {
//       workingHours = calculateWorkingHours(
//           todayRecord!['dayIn'], todayRecord!['dayOut']);
//     }

//     return Scaffold(
//       appBar: AppBar(
//         title: Text("Welcome ${widget.user['username']}"),
//         actions: [
//           IconButton(
//             icon: Icon(Icons.logout),
//             onPressed: () {
//               Navigator.pushAndRemoveUntil(
//                 context,
//                 MaterialPageRoute(builder: (_) => LoginScreen()),
//                 (route) => false,
//               );
//             },
//           ),
//         ],
//       ),
//       body: Padding(
//         padding: const EdgeInsets.all(20),
//         child: Column(
//           crossAxisAlignment: CrossAxisAlignment.start,
//           children: [
//             Text("Date: $today", style: TextStyle(fontSize: 18)),
//             SizedBox(height: 20),
//             ElevatedButton(
//               onPressed: isInDone ? null : markIn,
//               child: Text("Day In"),
//             ),
//             ElevatedButton(
//               onPressed: isOutDone || !isInDone ? null : markOut,
//               child: Text("Day Out"),
//             ),
//             SizedBox(height: 20),
//             if (isInDone || isOutDone)
//               Card(
//                 child: ListTile(
//                   title: Text("Today’s Attendance"),
//                   subtitle: Column(
//                     crossAxisAlignment: CrossAxisAlignment.start,
//                     children: [
//                       Text("In: ${todayRecord!['dayIn'] ?? '--'}"),
//                       Text("Out: ${todayRecord!['dayOut'] ?? '--'}"),
//                       Text("Worked: $workingHours"),
//                     ],
//                   ),
//                 ),
//               ),
//           ],
//         ),
//       ),
//     );
//   }
// }





// class CustomScratcher extends StatelessWidget {
//   const CustomScratcher({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return Scratcher(
//       brushSize: 30,
//       threshold: 50,
//       color: const Color(0xFF353F48),
//       onChange: (value) {},
//       onThreshold: () {},
//       child: Container(
//         height: 300,
//         width: 300,
//         color: Colors.white,
//         alignment: Alignment.center,
//         child: Image.asset("assets/images/app_icon.png")
//       ),
//     );
//   }
// }



// import 'package:flutter/material.dart';

// void main() {
//   runApp(TrainingInstituteApp());
// }

// class TrainingInstituteApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'TechLearn Institute',
//       theme: ThemeData(
//         primarySwatch: Colors.blue,
//         visualDensity: VisualDensity.adaptivePlatformDensity,
//       ),
//       home: SplashScreen(),
//       routes: {
//         '/login': (context) => LoginScreen(),
//         '/student-dashboard': (context) => StudentDashboard(),
//         '/admin-dashboard': (context) => AdminDashboard(),
//         '/courses': (context) => CoursesScreen(),
//         '/course-detail': (context) => CourseDetailScreen(),
//       },
//     );
//   }
// }

// // Splash Screen
// class SplashScreen extends StatefulWidget {
//   @override
//   _SplashScreenState createState() => _SplashScreenState();
// }

// class _SplashScreenState extends State<SplashScreen> {
//   @override
//   void initState() {
//     super.initState();
//     Future.delayed(Duration(seconds: 3), () {
//       Navigator.pushReplacement(
//         context,
//         MaterialPageRoute(builder: (context) => HomeScreen()),
//       );
//     });
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.blue[900],
//       body: Center(
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Icon(
//               Icons.school,
//               size: 100,
//               color: Colors.white,
//             ),
//             SizedBox(height: 20),
//             Text(
//               'TechLearn Institute',
//               style: TextStyle(
//                 fontSize: 28,
//                 fontWeight: FontWeight.bold,
//                 color: Colors.white,
//               ),
//             ),
//             SizedBox(height: 10),
//             Text(
//               'Master Technology Skills',
//               style: TextStyle(
//                 fontSize: 16,
//                 color: Colors.white70,
//               ),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Home Screen
// class HomeScreen extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('TechLearn Institute'),
//         backgroundColor: Colors.blue[900],
//         elevation: 0,
//       ),
//       body: SingleChildScrollView(
//         child: Column(
//           crossAxisAlignment: CrossAxisAlignment.start,
//           children: [
//             // Header Section
//             Container(
//               width: double.infinity,
//               padding: EdgeInsets.all(20),
//               decoration: BoxDecoration(
//                 gradient: LinearGradient(
//                   colors: [Colors.blue[900]!, Colors.blue[700]!],
//                   begin: Alignment.topCenter,
//                   end: Alignment.bottomCenter,
//                 ),
//               ),
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text(
//                     'Welcome to TechLearn',
//                     style: TextStyle(
//                       fontSize: 24,
//                       fontWeight: FontWeight.bold,
//                       color: Colors.white,
//                     ),
//                   ),
//                   SizedBox(height: 10),
//                   Text(
//                     'Master Full-Stack Development, Mobile Apps, and More!',
//                     style: TextStyle(
//                       fontSize: 16,
//                       color: Colors.white70,
//                     ),
//                   ),
//                   SizedBox(height: 20),
//                   Row(
//                     children: [
//                       Expanded(
//                         child: ElevatedButton(
//                           onPressed: () => Navigator.pushNamed(context, '/login'),
//                           child: Text('Student Login'),
//                           style: ElevatedButton.styleFrom(
//                             backgroundColor: Colors.orange,
//                             padding: EdgeInsets.symmetric(vertical: 15),
//                           ),
//                         ),
//                       ),
//                       SizedBox(width: 10),
//                       Expanded(
//                         child: ElevatedButton(
//                           onPressed: () => Navigator.pushNamed(context, '/login'),
//                           child: Text('Admin Login'),
//                           style: ElevatedButton.styleFrom(
//                             backgroundColor: Colors.green,
//                             padding: EdgeInsets.symmetric(vertical: 15),
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ],
//               ),
//             ),
            
//             // Quick Stats
//             Container(
//               padding: EdgeInsets.all(20),
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text(
//                     'Why Choose Us?',
//                     style: TextStyle(
//                       fontSize: 22,
//                       fontWeight: FontWeight.bold,
//                     ),
//                   ),
//                   SizedBox(height: 15),
//                   Row(
//                     children: [
//                       Expanded(
//                         child: _buildStatCard('500+', 'Students', Colors.blue),
//                       ),
//                       SizedBox(width: 10),
//                       Expanded(
//                         child: _buildStatCard('15+', 'Courses', Colors.green),
//                       ),
//                       SizedBox(width: 10),
//                       Expanded(
//                         child: _buildStatCard('95%', 'Success Rate', Colors.orange),
//                       ),
//                     ],
//                   ),
//                 ],
//               ),
//             ),

//             // Featured Courses
//             Container(
//               padding: EdgeInsets.symmetric(horizontal: 20),
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text(
//                     'Featured Courses',
//                     style: TextStyle(
//                       fontSize: 22,
//                       fontWeight: FontWeight.bold,
//                     ),
//                   ),
//                   SizedBox(height: 15),
//                   _buildCourseCard(
//                     'Full-Stack Development',
//                     'Learn MERN Stack, Django, and more',
//                     '6 months',
//                     Colors.purple,
//                     context,
//                   ),
//                   SizedBox(height: 10),
//                   _buildCourseCard(
//                     'Flutter Mobile Development',
//                     'Build iOS and Android apps with Flutter',
//                     '4 months',
//                     Colors.cyan,
//                     context,
//                   ),
//                   SizedBox(height: 10),
//                   _buildCourseCard(
//                     'Data Science & AI',
//                     'Python, Machine Learning, Deep Learning',
//                     '8 months',
//                     Colors.indigo,
//                     context,
//                   ),
//                 ],
//               ),
//             ),

//             SizedBox(height: 20),
//             Center(
//               child: ElevatedButton(
//                 onPressed: () => Navigator.pushNamed(context, '/courses'),
//                 child: Text('View All Courses'),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.blue[900],
//                   padding: EdgeInsets.symmetric(horizontal: 40, vertical: 15),
//                 ),
//               ),
//             ),
//             SizedBox(height: 30),
//           ],
//         ),
//       ),
//     );
//   }

//   Widget _buildStatCard(String number, String label, Color color) {
//     return Container(
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: color.withOpacity(0.1),
//         borderRadius: BorderRadius.circular(10),
//         border: Border.all(color: color.withOpacity(0.3)),
//       ),
//       child: Column(
//         children: [
//           Text(
//             number,
//             style: TextStyle(
//               fontSize: 24,
//               fontWeight: FontWeight.bold,
//               color: color,
//             ),
//           ),
//           Text(
//             label,
//             style: TextStyle(
//               fontSize: 12,
//               color: Colors.grey[600],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildCourseCard(String title, String description, String duration, Color color, BuildContext context) {
//     return InkWell(
//       onTap: () => Navigator.pushNamed(context, '/course-detail'),
//       child: Container(
//         padding: EdgeInsets.all(15),
//         decoration: BoxDecoration(
//           color: Colors.white,
//           borderRadius: BorderRadius.circular(10),
//           boxShadow: [
//             BoxShadow(
//               color: Colors.grey.withOpacity(0.2),
//               spreadRadius: 1,
//               blurRadius: 5,
//               offset: Offset(0, 2),
//             ),
//           ],
//         ),
//         child: Row(
//           children: [
//             Container(
//               width: 50,
//               height: 50,
//               decoration: BoxDecoration(
//                 color: color.withOpacity(0.2),
//                 borderRadius: BorderRadius.circular(25),
//               ),
//               child: Icon(Icons.code, color: color),
//             ),
//             SizedBox(width: 15),
//             Expanded(
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text(
//                     title,
//                     style: TextStyle(
//                       fontSize: 16,
//                       fontWeight: FontWeight.bold,
//                     ),
//                   ),
//                   Text(
//                     description,
//                     style: TextStyle(
//                       fontSize: 12,
//                       color: Colors.grey[600],
//                     ),
//                   ),
//                   SizedBox(height: 5),
//                   Text(
//                     'Duration: $duration',
//                     style: TextStyle(
//                       fontSize: 12,
//                       color: color,
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//             Icon(Icons.arrow_forward_ios, color: Colors.grey[400], size: 16),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Login Screen
// class LoginScreen extends StatefulWidget {
//   @override
//   _LoginScreenState createState() => _LoginScreenState();
// }

// class _LoginScreenState extends State<LoginScreen> {
//   final _emailController = TextEditingController();
//   final _passwordController = TextEditingController();
//   bool isStudent = true;

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Login'),
//         backgroundColor: Colors.blue[900],
//       ),
//       body: Padding(
//         padding: EdgeInsets.all(20),
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Icon(
//               Icons.account_circle,
//               size: 100,
//               color: Colors.blue[900],
//             ),
//             SizedBox(height: 30),
            
//             // Toggle between Student and Admin
//             Row(
//               mainAxisAlignment: MainAxisAlignment.center,
//               children: [
//                 ChoiceChip(
//                   label: Text('Student'),
//                   selected: isStudent,
//                   onSelected: (selected) => setState(() => isStudent = true),
//                 ),
//                 SizedBox(width: 20),
//                 ChoiceChip(
//                   label: Text('Admin'),
//                   selected: !isStudent,
//                   onSelected: (selected) => setState(() => isStudent = false),
//                 ),
//               ],
//             ),
            
//             SizedBox(height: 30),
            
//             TextField(
//               controller: _emailController,
//               decoration: InputDecoration(
//                 labelText: 'Email',
//                 prefixIcon: Icon(Icons.email),
//                 border: OutlineInputBorder(),
//               ),
//             ),
//             SizedBox(height: 20),
//             TextField(
//               controller: _passwordController,
//               decoration: InputDecoration(
//                 labelText: 'Password',
//                 prefixIcon: Icon(Icons.lock),
//                 border: OutlineInputBorder(),
//               ),
//               obscureText: true,
//             ),
//             SizedBox(height: 30),
            
//             SizedBox(
//               width: double.infinity,
//               child: ElevatedButton(
//                 onPressed: () {
//                   // Simple validation - in real app, validate against backend
//                   if (_emailController.text.isNotEmpty && _passwordController.text.isNotEmpty) {
//                     if (isStudent) {
//                       Navigator.pushReplacementNamed(context, '/student-dashboard');
//                     } else {
//                       Navigator.pushReplacementNamed(context, '/admin-dashboard');
//                     }
//                   } else {
//                     ScaffoldMessenger.of(context).showSnackBar(
//                       SnackBar(content: Text('Please fill all fields')),
//                     );
//                   }
//                 },
//                 child: Text('Login as ${isStudent ? 'Student' : 'Admin'}'),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.blue[900],
//                   padding: EdgeInsets.symmetric(vertical: 15),
//                 ),
//               ),
//             ),
            
//             SizedBox(height: 20),
//             TextButton(
//               onPressed: () {
//                 // Navigate to registration screen
//               },
//               child: Text('Don\'t have an account? Register here'),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Student Dashboard
// class StudentDashboard extends StatefulWidget {
//   @override
//   _StudentDashboardState createState() => _StudentDashboardState();
// }

// class _StudentDashboardState extends State<StudentDashboard> {
//   int _currentIndex = 0;
  
//   final List<Widget> _screens = [
//     StudentHomeTab(),
//     StudentCoursesTab(),
//     StudentScheduleTab(),
//     StudentProfileTab(),
//   ];

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Student Dashboard'),
//         backgroundColor: Colors.blue[900],
//         automaticallyImplyLeading: false,
//         actions: [
//           IconButton(
//             icon: Icon(Icons.logout),
//             onPressed: () => Navigator.pushReplacementNamed(context, '/'),
//           ),
//         ],
//       ),
//       body: _screens[_currentIndex],
//       bottomNavigationBar: BottomNavigationBar(
//         currentIndex: _currentIndex,
//         onTap: (index) => setState(() => _currentIndex = index),
//         type: BottomNavigationBarType.fixed,
//         items: [
//           BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
//           BottomNavigationBarItem(icon: Icon(Icons.book), label: 'Courses'),
//           BottomNavigationBarItem(icon: Icon(Icons.schedule), label: 'Schedule'),
//           BottomNavigationBarItem(icon: Icon(Icons.person), label: 'Profile'),
//         ],
//       ),
//     );
//   }
// }

// class StudentHomeTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             'Welcome back, John!',
//             style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(height: 20),
          
//           // Progress Card
//           Container(
//             width: double.infinity,
//             padding: EdgeInsets.all(20),
//             decoration: BoxDecoration(
//               gradient: LinearGradient(
//                 colors: [Colors.blue[700]!, Colors.blue[900]!],
//               ),
//               borderRadius: BorderRadius.circular(15),
//             ),
//             child: Column(
//               crossAxisAlignment: CrossAxisAlignment.start,
//               children: [
//                 Text(
//                   'Current Course Progress',
//                   style: TextStyle(color: Colors.white, fontSize: 18),
//                 ),
//                 SizedBox(height: 10),
//                 Text(
//                   'Full-Stack Development',
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 16,
//                     fontWeight: FontWeight.bold,
//                   ),
//                 ),
//                 SizedBox(height: 10),
//                 LinearProgressIndicator(
//                   value: 0.65,
//                   backgroundColor: Colors.white30,
//                   valueColor: AlwaysStoppedAnimation<Color>(Colors.orange),
//                 ),
//                 SizedBox(height: 5),
//                 Text(
//                   '65% Complete',
//                   style: TextStyle(color: Colors.white70),
//                 ),
//               ],
//             ),
//           ),
          
//           SizedBox(height: 20),
          
//           // Quick Actions
//           Text(
//             'Quick Actions',
//             style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(height: 15),
          
//           Row(
//             children: [
//               Expanded(
//                 child: _buildActionCard(
//                   'Upcoming Classes',
//                   Icons.schedule,
//                   Colors.green,
//                   '3 classes today',
//                 ),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: _buildActionCard(
//                   'Assignments',
//                   Icons.assignment,
//                   Colors.orange,
//                   '2 pending',
//                 ),
//               ),
//             ],
//           ),
          
//           SizedBox(height: 15),
          
//           Row(
//             children: [
//               Expanded(
//                 child: _buildActionCard(
//                   'Grades',
//                   Icons.grade,
//                   Colors.blue,
//                   'View Results',
//                 ),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: _buildActionCard(
//                   'Support',
//                   Icons.help,
//                   Colors.purple,
//                   'Get Help',
//                 ),
//               ),
//             ],
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildActionCard(String title, IconData icon, Color color, String subtitle) {
//     return Container(
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: color.withOpacity(0.1),
//         borderRadius: BorderRadius.circular(10),
//         border: Border.all(color: color.withOpacity(0.3)),
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Icon(icon, color: color, size: 30),
//           SizedBox(height: 10),
//           Text(
//             title,
//             style: TextStyle(fontWeight: FontWeight.bold),
//           ),
//           Text(
//             subtitle,
//             style: TextStyle(color: Colors.grey[600], fontSize: 12),
//           ),
//         ],
//       ),
//     );
//   }
// }

// class StudentCoursesTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             'My Enrolled Courses',
//             style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(height: 20),
          
//           Expanded(
//             child: ListView(
//               children: [
//                 _buildMyCourseCard(
//                   'Full-Stack Development',
//                   'MERN Stack, APIs, Deployment',
//                   65,
//                   Colors.blue,
//                 ),
//                 SizedBox(height: 15),
//                 _buildMyCourseCard(
//                   'Flutter Development',
//                   'Dart, Widgets, State Management',
//                   30,
//                   Colors.cyan,
//                 ),
//                 SizedBox(height: 15),
//                 _buildMyCourseCard(
//                   'Python Basics',
//                   'Fundamentals, OOP, Libraries',
//                   90,
//                   Colors.green,
//                 ),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildMyCourseCard(String title, String description, int progress, Color color) {
//     return Container(
//       padding: EdgeInsets.all(20),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(15),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 5,
//             offset: Offset(0, 2),
//           ),
//         ],
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             children: [
//               Container(
//                 width: 50,
//                 height: 50,
//                 decoration: BoxDecoration(
//                   color: color.withOpacity(0.2),
//                   borderRadius: BorderRadius.circular(25),
//                 ),
//                 child: Icon(Icons.book, color: color),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: Column(
//                   crossAxisAlignment: CrossAxisAlignment.start,
//                   children: [
//                     Text(
//                       title,
//                       style: TextStyle(
//                         fontSize: 18,
//                         fontWeight: FontWeight.bold,
//                       ),
//                     ),
//                     Text(
//                       description,
//                       style: TextStyle(
//                         color: Colors.grey[600],
//                         fontSize: 14,
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//             ],
//           ),
//           SizedBox(height: 15),
//           Text(
//             'Progress: $progress%',
//             style: TextStyle(fontWeight: FontWeight.w500),
//           ),
//           SizedBox(height: 5),
//           LinearProgressIndicator(
//             value: progress / 100,
//             backgroundColor: Colors.grey[300],
//             valueColor: AlwaysStoppedAnimation<Color>(color),
//           ),
//           SizedBox(height: 15),
//           Row(
//             children: [
//               Expanded(
//                 child: ElevatedButton(
//                   onPressed: () {},
//                   child: Text('Continue Learning'),
//                   style: ElevatedButton.styleFrom(backgroundColor: color),
//                 ),
//               ),
//               SizedBox(width: 10),
//               ElevatedButton(
//                 onPressed: () {},
//                 child: Text('View Details'),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.grey[300],
//                   foregroundColor: Colors.black,
//                 ),
//               ),
//             ],
//           ),
//         ],
//       ),
//     );
//   }
// }

// class StudentScheduleTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             'This Week\'s Schedule',
//             style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(height: 20),
          
//           Expanded(
//             child: ListView(
//               children: [
//                 _buildScheduleCard('Monday', [
//                   ScheduleItem('Full-Stack Development', '10:00 AM - 12:00 PM', 'React Components'),
//                   ScheduleItem('Flutter Basics', '2:00 PM - 4:00 PM', 'State Management'),
//                 ]),
//                 SizedBox(height: 15),
//                 _buildScheduleCard('Tuesday', [
//                   ScheduleItem('Python Programming', '10:00 AM - 12:00 PM', 'OOP Concepts'),
//                 ]),
//                 SizedBox(height: 15),
//                 _buildScheduleCard('Wednesday', [
//                   ScheduleItem('Full-Stack Development', '10:00 AM - 12:00 PM', 'Backend APIs'),
//                   ScheduleItem('Project Work', '2:00 PM - 5:00 PM', 'Portfolio Building'),
//                 ]),
//                 SizedBox(height: 15),
//                 _buildScheduleCard('Thursday', [
//                   ScheduleItem('Flutter Advanced', '10:00 AM - 12:00 PM', 'Navigation & Routing'),
//                 ]),
//                 SizedBox(height: 15),
//                 _buildScheduleCard('Friday', [
//                   ScheduleItem('Code Review', '10:00 AM - 11:00 AM', 'Weekly Assessment'),
//                   ScheduleItem('Doubt Clearing', '2:00 PM - 3:00 PM', 'Q&A Session'),
//                 ]),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildScheduleCard(String day, List<ScheduleItem> items) {
//     return Container(
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(10),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 5,
//             offset: Offset(0, 2),
//           ),
//         ],
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             day,
//             style: TextStyle(
//               fontSize: 18,
//               fontWeight: FontWeight.bold,
//               color: Colors.blue[900],
//             ),
//           ),
//           SizedBox(height: 10),
//           ...items.map((item) => Padding(
//             padding: EdgeInsets.symmetric(vertical: 5),
//             child: Row(
//               children: [
//                 Container(
//                   width: 4,
//                   height: 40,
//                   decoration: BoxDecoration(
//                     color: Colors.blue,
//                     borderRadius: BorderRadius.circular(2),
//                   ),
//                 ),
//                 SizedBox(width: 15),
//                 Expanded(
//                   child: Column(
//                     crossAxisAlignment: CrossAxisAlignment.start,
//                     children: [
//                       Text(
//                         item.subject,
//                         style: TextStyle(fontWeight: FontWeight.w500),
//                       ),
//                       Text(
//                         item.time,
//                         style: TextStyle(color: Colors.grey[600], fontSize: 12),
//                       ),
//                       Text(
//                         item.topic,
//                         style: TextStyle(color: Colors.blue, fontSize: 12),
//                       ),
//                     ],
//                   ),
//                 ),
//               ],
//             ),
//           )).toList(),
//         ],
//       ),
//     );
//   }
// }

// class ScheduleItem {
//   final String subject;
//   final String time;
//   final String topic;

//   ScheduleItem(this.subject, this.time, this.topic);
// }

// class StudentProfileTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         children: [
//           CircleAvatar(
//             radius: 50,
//             backgroundColor: Colors.blue[100],
//             child: Text(
//               'JS',
//               style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
//             ),
//           ),
//           SizedBox(height: 20),
//           Text(
//             'John Smith',
//             style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
//           ),
//           Text(
//             'john.smith@email.com',
//             style: TextStyle(color: Colors.grey[600]),
//           ),
//           SizedBox(height: 30),
          
//           _buildProfileItem('Student ID', 'STU001234'),
//           _buildProfileItem('Enrolled Courses', '3 Active'),
//           _buildProfileItem('Batch', 'FS-2024-B1'),
//           _buildProfileItem('Join Date', 'January 15, 2024'),
//           _buildProfileItem('Phone', '+91 9876543210'),
          
//           SizedBox(height: 30),
          
//           SizedBox(
//             width: double.infinity,
//             child: ElevatedButton(
//               onPressed: () {},
//               child: Text('Edit Profile'),
//               style: ElevatedButton.styleFrom(
//                 backgroundColor: Colors.blue[900],
//                 padding: EdgeInsets.symmetric(vertical: 15),
//               ),
//             ),
//           ),
          
//           SizedBox(height: 10),
          
//           SizedBox(
//             width: double.infinity,
//             child: ElevatedButton(
//               onPressed: () {},
//               child: Text('Change Password'),
//               style: ElevatedButton.styleFrom(
//                 backgroundColor: Colors.grey[400],
//                 foregroundColor: Colors.black,
//                 padding: EdgeInsets.symmetric(vertical: 15),
//               ),
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildProfileItem(String label, String value) {
//     return Padding(
//       padding: EdgeInsets.symmetric(vertical: 8),
//       child: Row(
//         mainAxisAlignment: MainAxisAlignment.spaceBetween,
//         children: [
//           Text(
//             label,
//             style: TextStyle(fontWeight: FontWeight.w500),
//           ),
//           Text(
//             value,
//             style: TextStyle(color: Colors.grey[600]),
//           ),
//         ],
//       ),
//     );
//   }
// }

// // Admin Dashboard
// class AdminDashboard extends StatefulWidget {
//   @override
//   _AdminDashboardState createState() => _AdminDashboardState();
// }

// class _AdminDashboardState extends State<AdminDashboard> {
//   int _currentIndex = 0;
  
//   final List<Widget> _screens = [
//     AdminHomeTab(),
//     AdminStudentsTab(),
//     AdminCoursesTab(),
//     AdminScheduleTab(),
//   ];

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Admin Dashboard'),
//         backgroundColor: Colors.green[900],
//         automaticallyImplyLeading: false,
//         actions: [
//           IconButton(
//             icon: Icon(Icons.logout),
//             onPressed: () => Navigator.pushReplacementNamed(context, '/'),
//           ),
//         ],
//       ),
//       body: _screens[_currentIndex],
//       bottomNavigationBar: BottomNavigationBar(
//         currentIndex: _currentIndex,
//         onTap: (index) => setState(() => _currentIndex = index),
//         type: BottomNavigationBarType.fixed,
//         items: [
//           BottomNavigationBarItem(icon: Icon(Icons.dashboard), label: 'Dashboard'),
//           BottomNavigationBarItem(icon: Icon(Icons.people), label: 'Students'),
//           BottomNavigationBarItem(icon: Icon(Icons.book), label: 'Courses'),
//           BottomNavigationBarItem(icon: Icon(Icons.schedule), label: 'Schedule'),
//         ],
//       ),
//     );
//   }
// }

// class AdminHomeTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             'Admin Dashboard',
//             style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(height: 20),
          
//           // Stats Cards
//           Row(
//             children: [
//               Expanded(
//                 child: _buildStatCard('Total Students', '487', Icons.people, Colors.blue),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: _buildStatCard('Active Courses', '12', Icons.book, Colors.green),
//               ),
//             ],
//           ),
          
//           SizedBox(height: 15),
          
//           Row(
//             children: [
//               Expanded(
//                 child: _buildStatCard('Total Batches', '8', Icons.group, Colors.orange),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: _buildStatCard('Revenue', '₹12.5L', Icons.attach_money, Colors.purple),
//               ),
//             ],
//           ),
          
//           SizedBox(height: 30),
          
//           Text(
//             'Recent Activities',
//             style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(height: 15),
          
//           Expanded(
//             child: ListView(
//               children: [
//                 _buildActivityItem(
//                   'New student enrolled in Full-Stack Development',
//                   '2 hours ago',
//                   Icons.person_add,
//                   Colors.green,
//                 ),
//                 _buildActivityItem(
//                   'Flutter batch completed Module 3',
//                   '4 hours ago',
//                   Icons.check_circle,
//                   Colors.blue,
//                 ),
//                 _buildActivityItem(
//                   'Assignment submitted by 25 students',
//                   '1 day ago',
//                   Icons.assignment_turned_in,
//                   Colors.orange,
//                 ),
//                 _buildActivityItem(
//                   'New course "React Native" added',
//                   '2 days ago',
//                   Icons.add_circle,
//                   Colors.purple,
//                 ),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildStatCard(String title, String value, IconData icon, Color color) {
//     return Container(
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: color.withOpacity(0.1),
//         borderRadius: BorderRadius.circular(10),
//         border: Border.all(color: color.withOpacity(0.3)),
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Icon(icon, color: color, size: 30),
//           SizedBox(height: 10),
//           Text(
//             value,
//             style: TextStyle(
//               fontSize: 24,
//               fontWeight: FontWeight.bold,
//               color: color,
//             ),
//           ),
//           Text(
//             title,
//             style: TextStyle(
//               color: Colors.grey[600],
//               fontSize: 12,
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildActivityItem(String activity, String time, IconData icon, Color color) {
//     return Container(
//       margin: EdgeInsets.only(bottom: 10),
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(10),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.1),
//             spreadRadius: 1,
//             blurRadius: 3,
//             offset: Offset(0, 1),
//           ),
//         ],
//       ),
//       child: Row(
//         children: [
//           Icon(icon, color: color, size: 20),
//           SizedBox(width: 15),
//           Expanded(
//             child: Column(
//               crossAxisAlignment: CrossAxisAlignment.start,
//               children: [
//                 Text(
//                   activity,
//                   style: TextStyle(fontWeight: FontWeight.w500),
//                 ),
//                 Text(
//                   time,
//                   style: TextStyle(color: Colors.grey[600], fontSize: 12),
//                 ),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }
// }

// class AdminStudentsTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               Text(
//                 'Students Management',
//                 style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
//               ),
//               ElevatedButton(
//                 onPressed: () {},
//                 child: Text('Add Student'),
//                 style: ElevatedButton.styleFrom(backgroundColor: Colors.green),
//               ),
//             ],
//           ),
//           SizedBox(height: 20),
          
//           TextField(
//             decoration: InputDecoration(
//               hintText: 'Search students...',
//               prefixIcon: Icon(Icons.search),
//               border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
//             ),
//           ),
//           SizedBox(height: 20),
          
//           Expanded(
//             child: ListView(
//               children: [
//                 _buildStudentCard('John Smith', 'john@email.com', 'Full-Stack Dev', 'Active'),
//                 _buildStudentCard('Sarah Johnson', 'sarah@email.com', 'Flutter Dev', 'Active'),
//                 _buildStudentCard('Mike Chen', 'mike@email.com', 'Data Science', 'Completed'),
//                 _buildStudentCard('Emily Davis', 'emily@email.com', 'Full-Stack Dev', 'Active'),
//                 _buildStudentCard('Alex Wilson', 'alex@email.com', 'Flutter Dev', 'Paused'),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildStudentCard(String name, String email, String course, String status) {
//     Color statusColor = status == 'Active' 
//         ? Colors.green 
//         : status == 'Completed' 
//             ? Colors.blue 
//             : Colors.orange;
    
//     return Container(
//       margin: EdgeInsets.only(bottom: 15),
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(10),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 5,
//             offset: Offset(0, 2),
//           ),
//         ],
//       ),
//       child: Row(
//         children: [
//           CircleAvatar(
//             backgroundColor: Colors.blue[100],
//             child: Text(name.substring(0, 1)),
//           ),
//           SizedBox(width: 15),
//           Expanded(
//             child: Column(
//               crossAxisAlignment: CrossAxisAlignment.start,
//               children: [
//                 Text(
//                   name,
//                   style: TextStyle(fontWeight: FontWeight.bold),
//                 ),
//                 Text(
//                   email,
//                   style: TextStyle(color: Colors.grey[600], fontSize: 12),
//                 ),
//                 Text(
//                   course,
//                   style: TextStyle(color: Colors.blue, fontSize: 12),
//                 ),
//               ],
//             ),
//           ),
//           Container(
//             padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
//             decoration: BoxDecoration(
//               color: statusColor.withOpacity(0.2),
//               borderRadius: BorderRadius.circular(15),
//             ),
//             child: Text(
//               status,
//               style: TextStyle(
//                 color: statusColor,
//                 fontSize: 12,
//                 fontWeight: FontWeight.w500,
//               ),
//             ),
//           ),
//         ],
//       ),
//     );
//   }
// }

// class AdminCoursesTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               Text(
//                 'Course Management',
//                 style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
//               ),
//               ElevatedButton(
//                 onPressed: () {},
//                 child: Text('Add Course'),
//                 style: ElevatedButton.styleFrom(backgroundColor: Colors.green),
//               ),
//             ],
//           ),
//           SizedBox(height: 20),
          
//           Expanded(
//             child: ListView(
//               children: [
//                 _buildAdminCourseCard(
//                   'Full-Stack Development',
//                   'Complete MERN Stack with deployment',
//                   '6 months',
//                   '₹45,000',
//                   156,
//                   Colors.blue,
//                 ),
//                 _buildAdminCourseCard(
//                   'Flutter Mobile Development',
//                   'Cross-platform app development',
//                   '4 months',
//                   '₹35,000',
//                   89,
//                   Colors.cyan,
//                 ),
//                 _buildAdminCourseCard(
//                   'Data Science & AI',
//                   'Python, ML, Deep Learning',
//                   '8 months',
//                   '₹55,000',
//                   67,
//                   Colors.purple,
//                 ),
//                 _buildAdminCourseCard(
//                   'React Native',
//                   'Native mobile apps with React',
//                   '3 months',
//                   '₹30,000',
//                   45,
//                   Colors.orange,
//                 ),
//                 _buildAdminCourseCard(
//                   'Python Programming',
//                   'Fundamentals to advanced concepts',
//                   '4 months',
//                   '₹25,000',
//                   78,
//                   Colors.green,
//                 ),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildAdminCourseCard(
//     String title,
//     String description,
//     String duration,
//     String fee,
//     int enrolled,
//     Color color,
//   ) {
//     return Container(
//       margin: EdgeInsets.only(bottom: 15),
//       padding: EdgeInsets.all(20),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(15),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 5,
//             offset: Offset(0, 2),
//           ),
//         ],
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             children: [
//               Container(
//                 width: 50,
//                 height: 50,
//                 decoration: BoxDecoration(
//                   color: color.withOpacity(0.2),
//                   borderRadius: BorderRadius.circular(25),
//                 ),
//                 child: Icon(Icons.code, color: color),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: Column(
//                   crossAxisAlignment: CrossAxisAlignment.start,
//                   children: [
//                     Text(
//                       title,
//                       style: TextStyle(
//                         fontSize: 18,
//                         fontWeight: FontWeight.bold,
//                       ),
//                     ),
//                     Text(
//                       description,
//                       style: TextStyle(
//                         color: Colors.grey[600],
//                         fontSize: 14,
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//             ],
//           ),
//           SizedBox(height: 15),
//           Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text('Duration: $duration'),
//                   Text('Fee: $fee'),
//                   Text('Enrolled: $enrolled students'),
//                 ],
//               ),
//             ],
//           ),
//           SizedBox(height: 15),
//           Row(
//             children: [
//               Expanded(
//                 child: ElevatedButton(
//                   onPressed: () {},
//                   child: Text('Edit Course'),
//                   style: ElevatedButton.styleFrom(backgroundColor: color),
//                 ),
//               ),
//               SizedBox(width: 10),
//               ElevatedButton(
//                 onPressed: () {},
//                 child: Text('View Students'),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.grey[300],
//                   foregroundColor: Colors.black,
//                 ),
//               ),
//             ],
//           ),
//         ],
//       ),
//     );
//   }
// }

// class AdminScheduleTab extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Padding(
//       padding: EdgeInsets.all(20),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               Text(
//                 'Schedule Management',
//                 style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
//               ),
//               ElevatedButton(
//                 onPressed: () {},
//                 child: Text('Add Class'),
//                 style: ElevatedButton.styleFrom(backgroundColor: Colors.green),
//               ),
//             ],
//           ),
//           SizedBox(height: 20),
          
//           Expanded(
//             child: ListView(
//               children: [
//                 _buildAdminScheduleCard('Monday', [
//                   AdminScheduleItem('Full-Stack Dev - Batch A', '10:00 AM - 12:00 PM', 'Room 101', 'John Doe'),
//                   AdminScheduleItem('Flutter - Batch B', '2:00 PM - 4:00 PM', 'Room 102', 'Jane Smith'),
//                 ]),
//                 SizedBox(height: 15),
//                 _buildAdminScheduleCard('Tuesday', [
//                   AdminScheduleItem('Data Science - Batch A', '10:00 AM - 1:00 PM', 'Room 103', 'Mike Wilson'),
//                   AdminScheduleItem('Python - Batch C', '3:00 PM - 5:00 PM', 'Room 101', 'Sarah Connor'),
//                 ]),
//                 SizedBox(height: 15),
//                 _buildAdminScheduleCard('Wednesday', [
//                   AdminScheduleItem('Full-Stack Dev - Batch A', '10:00 AM - 12:00 PM', 'Room 101', 'John Doe'),
//                   AdminScheduleItem('React Native - Batch D', '2:00 PM - 4:00 PM', 'Room 104', 'Alex Turner'),
//                 ]),
//               ],
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildAdminScheduleCard(String day, List<AdminScheduleItem> items) {
//     return Container(
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(10),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 5,
//             offset: Offset(0, 2),
//           ),
//         ],
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             day,
//             style: TextStyle(
//               fontSize: 18,
//               fontWeight: FontWeight.bold,
//               color: Colors.green[900],
//             ),
//           ),
//           SizedBox(height: 10),
//           ...items.map((item) => Container(
//             margin: EdgeInsets.symmetric(vertical: 8),
//             padding: EdgeInsets.all(12),
//             decoration: BoxDecoration(
//               color: Colors.green[50],
//               borderRadius: BorderRadius.circular(8),
//               // border: Border.left(color: Colors.green, width: 4),
//             ),
//             child: Column(
//               crossAxisAlignment: CrossAxisAlignment.start,
//               children: [
//                 Text(
//                   item.course,
//                   style: TextStyle(fontWeight: FontWeight.bold),
//                 ),
//                 SizedBox(height: 5),
//                 Row(
//                   children: [
//                     Icon(Icons.access_time, size: 16, color: Colors.grey[600]),
//                     SizedBox(width: 5),
//                     Text(
//                       item.time,
//                       style: TextStyle(color: Colors.grey[600], fontSize: 12),
//                     ),
//                     SizedBox(width: 20),
//                     Icon(Icons.room, size: 16, color: Colors.grey[600]),
//                     SizedBox(width: 5),
//                     Text(
//                       item.room,
//                       style: TextStyle(color: Colors.grey[600], fontSize: 12),
//                     ),
//                   ],
//                 ),
//                 SizedBox(height: 5),
//                 Text(
//                   'Instructor: ${item.instructor}',
//                   style: TextStyle(color: Colors.green[700], fontSize: 12),
//                 ),
//               ],
//             ),
//           )).toList(),
//         ],
//       ),
//     );
//   }
// }

// class AdminScheduleItem {
//   final String course;
//   final String time;
//   final String room;
//   final String instructor;

//   AdminScheduleItem(this.course, this.time, this.room, this.instructor);
// }

// // Courses Screen
// class CoursesScreen extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('All Courses'),
//         backgroundColor: Colors.blue[900],
//       ),
//       body: Padding(
//         padding: EdgeInsets.all(20),
//         child: Column(
//           children: [
//             TextField(
//               decoration: InputDecoration(
//                 hintText: 'Search courses...',
//                 prefixIcon: Icon(Icons.search),
//                 border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
//               ),
//             ),
//             SizedBox(height: 20),
            
//             Expanded(
//               child: ListView(
//                 children: [
//                   _buildCourseCard(
//                     context,
//                     'Full-Stack Web Development',
//                     'Master MERN Stack, APIs, Deployment',
//                     '6 months',
//                     '₹45,000',
//                     4.8,
//                     156,
//                     Colors.blue,
//                   ),
//                   _buildCourseCard(
//                     context,
//                     'Flutter Mobile Development',
//                     'Build iOS & Android apps with Flutter',
//                     '4 months',
//                     '₹35,000',
//                     4.7,
//                     89,
//                     Colors.cyan,
//                   ),
//                   _buildCourseCard(
//                     context,
//                     'Data Science & AI',
//                     'Python, Machine Learning, Deep Learning',
//                     '8 months',
//                     '₹55,000',
//                     4.9,
//                     67,
//                     Colors.purple,
//                   ),
//                   _buildCourseCard(
//                     context,
//                     'React Native Development',
//                     'Cross-platform mobile apps with React',
//                     '3 months',
//                     '₹30,000',
//                     4.6,
//                     45,
//                     Colors.orange,
//                   ),
//                   _buildCourseCard(
//                     context,
//                     'Python Programming',
//                     'From basics to advanced concepts',
//                     '4 months',
//                     '₹25,000',
//                     4.5,
//                     78,
//                     Colors.green,
//                   ),
//                 ],
//               ),
//             ),
//           ],
//         ),
//       ),
//     );
//   }

//   Widget _buildCourseCard(
//     BuildContext context,
//     String title,
//     String description,
//     String duration,
//     String fee,
//     double rating,
//     int students,
//     Color color,
//   ) {
//     return Container(
//       margin: EdgeInsets.only(bottom: 20),
//       padding: EdgeInsets.all(20),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(15),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 8,
//             offset: Offset(0, 3),
//           ),
//         ],
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             children: [
//               Container(
//                 width: 60,
//                 height: 60,
//                 decoration: BoxDecoration(
//                   color: color.withOpacity(0.2),
//                   borderRadius: BorderRadius.circular(30),
//                 ),
//                 child: Icon(Icons.code, color: color, size: 30),
//               ),
//               SizedBox(width: 15),
//               Expanded(
//                 child: Column(
//                   crossAxisAlignment: CrossAxisAlignment.start,
//                   children: [
//                     Text(
//                       title,
//                       style: TextStyle(
//                         fontSize: 18,
//                         fontWeight: FontWeight.bold,
//                       ),
//                     ),
//                     Text(
//                       description,
//                       style: TextStyle(
//                         color: Colors.grey[600],
//                         fontSize: 14,
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//             ],
//           ),
//           SizedBox(height: 15),
          
//           Row(
//             children: [
//               Icon(Icons.star, color: Colors.orange, size: 16),
//               Text(
//                 ' $rating',
//                 style: TextStyle(fontWeight: FontWeight.w500),
//               ),
//               SizedBox(width: 15),
//               Text(
//                 '$students students',
//                 style: TextStyle(color: Colors.grey[600], fontSize: 12),
//               ),
//             ],
//           ),
          
//           SizedBox(height: 15),
          
//           Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text(
//                     'Duration: $duration',
//                     style: TextStyle(fontWeight: FontWeight.w500),
//                   ),
//                   Text(
//                     'Fee: $fee',
//                     style: TextStyle(
//                       color: color,
//                       fontWeight: FontWeight.bold,
//                       fontSize: 16,
//                     ),
//                   ),
//                 ],
//               ),
//               ElevatedButton(
//                 onPressed: () => Navigator.pushNamed(context, '/course-detail'),
//                 child: Text('View Details'),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: color,
//                   shape: RoundedRectangleBorder(
//                     borderRadius: BorderRadius.circular(20),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ],
//       ),
//     );
//   }
// }

// // Course Detail Screen
// class CourseDetailScreen extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Course Details'),
//         backgroundColor: Colors.blue[900],
//       ),
//       body: SingleChildScrollView(
//         padding: EdgeInsets.all(20),
//         child: Column(
//           crossAxisAlignment: CrossAxisAlignment.start,
//           children: [
//             // Course Header
//             Container(
//               width: double.infinity,
//               padding: EdgeInsets.all(20),
//               decoration: BoxDecoration(
//                 gradient: LinearGradient(
//                   colors: [Colors.blue[700]!, Colors.blue[900]!],
//                 ),
//                 borderRadius: BorderRadius.circular(15),
//               ),
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   Text(
//                     'Full-Stack Web Development',
//                     style: TextStyle(
//                       color: Colors.white,
//                       fontSize: 24,
//                       fontWeight: FontWeight.bold,
//                     ),
//                   ),
//                   SizedBox(height: 10),
//                   Text(
//                     'Master MERN Stack, APIs, and Deployment',
//                     style: TextStyle(
//                       color: Colors.white70,
//                       fontSize: 16,
//                     ),
//                   ),
//                   SizedBox(height: 15),
//                   Row(
//                     children: [
//                       Icon(Icons.star, color: Colors.orange, size: 20),
//                       Text(
//                         ' 4.8 (156 students)',
//                         style: TextStyle(color: Colors.white),
//                       ),
//                     ],
//                   ),
//                 ],
//               ),
//             ),
            
//             SizedBox(height: 20),
            
//             // Course Info
//             Row(
//               children: [
//                 Expanded(
//                   child: _buildInfoCard('Duration', '6 Months', Icons.access_time),
//                 ),
//                 SizedBox(width: 15),
//                 Expanded(
//                   child: _buildInfoCard('Fee', '₹45,000', Icons.currency_rupee),
//                 ),
//               ],
//             ),
            
//             SizedBox(height: 20),
            
//             // What You'll Learn
//             Text(
//               'What You\'ll Learn',
//               style: TextStyle(
//                 fontSize: 20,
//                 fontWeight: FontWeight.bold,
//               ),
//             ),
//             SizedBox(height: 15),
            
//             _buildLearningPoint('✓ HTML, CSS, JavaScript fundamentals'),
//             _buildLearningPoint('✓ React.js with Hooks and Context API'),
//             _buildLearningPoint('✓ Node.js and Express.js backend development'),
//             _buildLearningPoint('✓ MongoDB database design and operations'),
//             _buildLearningPoint('✓ RESTful API development and integration'),
//             _buildLearningPoint('✓ Authentication and authorization'),
//             _buildLearningPoint('✓ Deployment on AWS/Heroku'),
//             _buildLearningPoint('✓ Git version control and collaboration'),
            
//             SizedBox(height: 25),
            
//             // Curriculum
//             Text(
//               'Course Curriculum',
//               style: TextStyle(
//                 fontSize: 20,
//                 fontWeight: FontWeight.bold,
//               ),
//             ),
//             SizedBox(height: 15),
            
//             _buildModuleCard('Module 1: Frontend Fundamentals', '4 weeks', [
//               'HTML5 & CSS3',
//               'JavaScript ES6+',
//               'Responsive Design',
//               'Bootstrap Framework',
//             ]),
            
//             _buildModuleCard('Module 2: React Development', '6 weeks', [
//               'React Components & JSX',
//               'State Management',
//               'React Hooks',
//               'React Router',
//             ]),
            
//             _buildModuleCard('Module 3: Backend Development', '6 weeks', [
//               'Node.js Fundamentals',
//               'Express.js Framework',
//               'RESTful APIs',
//               'Database Integration',
//             ]),
            
//             _buildModuleCard('Module 4: Full-Stack Integration', '4 weeks', [
//               'Connecting Frontend & Backend',
//               'Authentication Systems',
//               'Error Handling',
//               'Testing & Debugging',
//             ]),
            
//             _buildModuleCard('Module 5: Deployment & DevOps', '4 weeks', [
//               'Cloud Deployment',
//               'CI/CD Pipelines',
//               'Performance Optimization',
//               'Monitoring & Maintenance',
//             ]),
            
//             SizedBox(height: 30),
            
//             // Enroll Button
//             SizedBox(
//               width: double.infinity,
//               child: ElevatedButton(
//                 onPressed: () {
//                   ScaffoldMessenger.of(context).showSnackBar(
//                     SnackBar(
//                       content: Text('Enrollment form opened! Contact admin for registration.'),
//                       backgroundColor: Colors.green,
//                     ),
//                   );
//                 },
//                 child: Text(
//                   'Enroll Now - ₹45,000',
//                   style: TextStyle(fontSize: 18),
//                 ),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.blue[900],
//                   padding: EdgeInsets.symmetric(vertical: 18),
//                   shape: RoundedRectangleBorder(
//                     borderRadius: BorderRadius.circular(10),
//                   ),
//                 ),
//               ),
//             ),
            
//             SizedBox(height: 15),
            
//             SizedBox(
//               width: double.infinity,
//               child: ElevatedButton(
//                 onPressed: () {},
//                 child: Text('Contact for More Info'),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.grey[400],
//                   foregroundColor: Colors.black,
//                   padding: EdgeInsets.symmetric(vertical: 15),
//                   shape: RoundedRectangleBorder(
//                     borderRadius: BorderRadius.circular(10),
//                   ),
//                 ),
//               ),
//             ),
            
//             SizedBox(height: 20),
//           ],
//         ),
//       ),
//     );
//   }

//   Widget _buildInfoCard(String label, String value, IconData icon) {
//     return Container(
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: Colors.blue[50],
//         borderRadius: BorderRadius.circular(10),
//         border: Border.all(color: Colors.blue.withOpacity(0.3)),
//       ),
//       child: Column(
//         children: [
//           Icon(icon, color: Colors.blue[900], size: 30),
//           SizedBox(height: 10),
//           Text(
//             value,
//             style: TextStyle(
//               fontSize: 18,
//               fontWeight: FontWeight.bold,
//               color: Colors.blue[900],
//             ),
//           ),
//           Text(
//             label,
//             style: TextStyle(color: Colors.grey[600]),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildLearningPoint(String text) {
//     return Padding(
//       padding: EdgeInsets.symmetric(vertical: 5),
//       child: Row(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Text(
//             text.substring(0, 1),
//             style: TextStyle(color: Colors.green, fontWeight: FontWeight.bold),
//           ),
//           SizedBox(width: 10),
//           Expanded(
//             child: Text(
//               text.substring(2),
//               style: TextStyle(fontSize: 14),
//             ),
//           ),
//         ],
//       ),
//     );
//   }

//   Widget _buildModuleCard(String title, String duration, List<String> topics) {
//     return Container(
//       margin: EdgeInsets.only(bottom: 15),
//       padding: EdgeInsets.all(15),
//       decoration: BoxDecoration(
//         color: Colors.white,
//         borderRadius: BorderRadius.circular(10),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 5,
//             offset: Offset(0, 2),
//           ),
//         ],
//       ),
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           Row(
//             mainAxisAlignment: MainAxisAlignment.spaceBetween,
//             children: [
//               Expanded(
//                 child: Text(
//                   title,
//                   style: TextStyle(
//                     fontWeight: FontWeight.bold,
//                     fontSize: 16,
//                   ),))])]));}}